services:
  - type: web
    name: rawad-almustaqbal-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /up
    autoDeployTrigger: commit
   # preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          name: rawad-almustaqbal-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: ENABLE_CLOUDINARY
        value: "true"
      - key: CLOUDINARY_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SANCTUM_STATEFUL_DOMAINS
        value: rawad-almustaqbal-api.onrender.com,rawad-almustaqbal-frontend.netlify.app,localhost:3000,localhost:5173
      - key: CORS_ALLOWED_ORIGINS
        value: https://rawad-almustaqbal-api.onrender.com,https://rawad-almustaqbal-frontend.netlify.app,http://localhost:3000,http://localhost:5173
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: rawad-almustaqbal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rawad-almustaqbal-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: rawad-almustaqbal-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: rawad-almustaqbal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rawad-almustaqbal-db
          property: password

databases:
  - name: rawad-almustaqbal-db
    plan: free